logo = """
                                                                 bbbbbbbb                                                                                                                                                                                                                                                                                           
NNNNNNNN        NNNNNNNN                                         b::::::b                                                                 GGGGGGGGGGGGG                                                                          iiii                                                    GGGGGGGGGGGGG                                                              
N:::::::N       N::::::N                                         b::::::b                                                              GGG::::::::::::G                                                                         i::::i                                                GGG::::::::::::G                                                              
N::::::::N      N::::::N                                         b::::::b                                                            GG:::::::::::::::G                                                                          iiii                                               GG:::::::::::::::G                                                              
N:::::::::N     N::::::N                                          b:::::b                                                           G:::::GGGGGGGG::::G                                                                                                                            G:::::GGGGGGGG::::G                                                              
N::::::::::N    N::::::Nuuuuuu    uuuuuu     mmmmmmm    mmmmmmm   b:::::bbbbbbbbb        eeeeeeeeeeee    rrrrr   rrrrrrrrr         G:::::G       GGGGGGuuuuuu    uuuuuu      eeeeeeeeeeee        ssssssssss       ssssssssss   iiiiiiinnnn  nnnnnnnn       ggggggggg   ggggg      G:::::G       GGGGGG  aaaaaaaaaaaaa      mmmmmmm    mmmmmmm       eeeeeeeeeeee    
N:::::::::::N   N::::::Nu::::u    u::::u   mm:::::::m  m:::::::mm b::::::::::::::bb    ee::::::::::::ee  r::::rrr:::::::::r       G:::::G              u::::u    u::::u    ee::::::::::::ee    ss::::::::::s    ss::::::::::s  i:::::in:::nn::::::::nn    g:::::::::ggg::::g     G:::::G                a::::::::::::a   mm:::::::m  m:::::::mm   ee::::::::::::ee  
N:::::::N::::N  N::::::Nu::::u    u::::u  m::::::::::mm::::::::::mb::::::::::::::::b  e::::::eeeee:::::eer:::::::::::::::::r      G:::::G              u::::u    u::::u   e::::::eeeee:::::eess:::::::::::::s ss:::::::::::::s  i::::in::::::::::::::nn  g:::::::::::::::::g     G:::::G                aaaaaaaaa:::::a m::::::::::mm::::::::::m e::::::eeeee:::::ee
N::::::N N::::N N::::::Nu::::u    u::::u  m::::::::::::::::::::::mb:::::bbbbb:::::::be::::::e     e:::::err::::::rrrrr::::::r     G:::::G    GGGGGGGGGGu::::u    u::::u  e::::::e     e:::::es::::::ssss:::::ss::::::ssss:::::s i::::inn:::::::::::::::ng::::::ggggg::::::gg     G:::::G    GGGGGGGGGG           a::::a m::::::::::::::::::::::me::::::e     e:::::e
N::::::N  N::::N:::::::Nu::::u    u::::u  m:::::mmm::::::mmm:::::mb:::::b    b::::::be:::::::eeeee::::::e r:::::r     r:::::r     G:::::G    G::::::::Gu::::u    u::::u  e:::::::eeeee::::::e s:::::s  ssssss  s:::::s  ssssss  i::::i  n:::::nnnn:::::ng:::::g     g:::::g      G:::::G    G::::::::G    aaaaaaa:::::a m:::::mmm::::::mmm:::::me:::::::eeeee::::::e
N::::::N   N:::::::::::Nu::::u    u::::u  m::::m   m::::m   m::::mb:::::b     b:::::be:::::::::::::::::e  r:::::r     rrrrrrr     G:::::G    GGGGG::::Gu::::u    u::::u  e:::::::::::::::::e    s::::::s         s::::::s       i::::i  n::::n    n::::ng:::::g     g:::::g      G:::::G    GGGGG::::G  aa::::::::::::a m::::m   m::::m   m::::me:::::::::::::::::e 
N::::::N    N::::::::::Nu::::u    u::::u  m::::m   m::::m   m::::mb:::::b     b:::::be::::::eeeeeeeeeee   r:::::r                 G:::::G        G::::Gu::::u    u::::u  e::::::eeeeeeeeeee        s::::::s         s::::::s    i::::i  n::::n    n::::ng:::::g     g:::::g      G:::::G        G::::G a::::aaaa::::::a m::::m   m::::m   m::::me::::::eeeeeeeeeee  
N::::::N     N:::::::::Nu:::::uuuu:::::u  m::::m   m::::m   m::::mb:::::b     b:::::be:::::::e            r:::::r                  G:::::G       G::::Gu:::::uuuu:::::u  e:::::::e           ssssss   s:::::s ssssss   s:::::s  i::::i  n::::n    n::::ng::::::g    g:::::g       G:::::G       G::::Ga::::a    a:::::a m::::m   m::::m   m::::me:::::::e           
N::::::N      N::::::::Nu:::::::::::::::uum::::m   m::::m   m::::mb:::::bbbbbb::::::be::::::::e           r:::::r                   G:::::GGGGGGGG::::Gu:::::::::::::::uue::::::::e          s:::::ssss::::::ss:::::ssss::::::si::::::i n::::n    n::::ng:::::::ggggg:::::g        G:::::GGGGGGGG::::Ga::::a    a:::::a m::::m   m::::m   m::::me::::::::e          
N::::::N       N:::::::N u:::::::::::::::um::::m   m::::m   m::::mb::::::::::::::::b  e::::::::eeeeeeee   r:::::r                    GG:::::::::::::::G u:::::::::::::::u e::::::::eeeeeeee  s::::::::::::::s s::::::::::::::s i::::::i n::::n    n::::n g::::::::::::::::g         GG:::::::::::::::Ga:::::aaaa::::::a m::::m   m::::m   m::::m e::::::::eeeeeeee  
N::::::N        N::::::N  uu::::::::uu:::um::::m   m::::m   m::::mb:::::::::::::::b    ee:::::::::::::e   r:::::r                      GGG::::::GGG:::G  uu::::::::uu:::u  ee:::::::::::::e   s:::::::::::ss   s:::::::::::ss  i::::::i n::::n    n::::n  gg::::::::::::::g           GGG::::::GGG:::G a::::::::::aa:::am::::m   m::::m   m::::m  ee:::::::::::::e  
NNNNNNNN         NNNNNNN    uuuuuuuu  uuuummmmmm   mmmmmm   mmmmmmbbbbbbbbbbbbbbbb       eeeeeeeeeeeeee   rrrrrrr                         GGGGGG   GGGG    uuuuuuuu  uuuu    eeeeeeeeeeeeee    sssssssssss      sssssssssss    iiiiiiii nnnnnn    nnnnnn    gggggggg::::::g              GGGGGG   GGGG  aaaaaaaaaa  aaaammmmmm   mmmmmm   mmmmmm    eeeeeeeeeeeeee  
                                                                                                                                                                                                                                                                    g:::::g                                                                                         
                                                                                                                                                                                                                                                        gggggg      g:::::g                                                                                         
                                                                                                                                                                                                                                                        g:::::gg   gg:::::g                                                                                         
                                                                                                                                                                                                                                                         g::::::ggg:::::::g                                                                                         
                                                                                                                                                                                                                                                          gg:::::::::::::g                                                                                          
                                                                                                                                                                                                                                                            ggg::::::ggg                                                                                            
                                                                                                                                                                                                                                                               gggggg                                                                                                                                                                                                                  
"""